name: 'Dingtalk Robot Message'
description: 'dingtalk robot message for github action'
author: 'fifsky@gmail.com'
inputs:
  url:
    description: 'dingtalk webhook'
    required: true

  type:
      description: 'type'
    default: 'markdown'

  content:
    description: 'content'
    required: true

  at:
    description: 'at somebody'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message-square"
