name: 'Dingtalk Robot Message'
description: 'dingtalk robot message for github action'
author: 'fifsky@gmail.com'
inputs:
  htmlFile:
    description: 'html file path'
    required: true

  outputFile:
    description: 'output file path'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message"