name: dingtalk

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dingtalk robot message
        uses: fifsky/dingtalk-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=7ad729aaf57c8f0fcd8c41b8c24e7dc2298b942c1909a51230ea457d205b54b9
          type: markdown
          content: |
          # 不要抄袭，啊，不要抄袭！

