name: dingtalk

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dingtalk robot message
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK}}
          type: markdown
          content: |
            # 发布频道推送
            ### 《Getting Over It》下载方式更改，只需下载一个文件即可
            ![img](https://raw.githubusercontent.com/Galaxy-Studio-Team/sources/master/Getting-Over-It/image-20200517083537434.png)
            ### [点击此处立即下载体验](https://galaxy-studio.ga/2020/05/16/GettingOverIt)
            > 星际工作室智能推送
