name: dingtalk

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dingtalk robot message
        uses: fifsky/dingtalk-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=6abdc4bfed1dd20c9d3a5d52894a1bb197e60971c5326b838cd5b3e9a5b1b5a4
          content: |
            # @郭智康 OK.
