name: dingtalk

on:
  status:
  create:
  watch:
    types: [started]
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: DingTalk Robot Action Message
        uses: Galaxy-Studio-Team/DingTalk-Robot-Action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK}}
          type: markdown
          content: |
            # Tips
            ## Galaxy-Studio-Code is Testing me.
            
