name: dingtalk

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dingtalk robot message
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK}}
          type: markdown
          content: |
            # 星际工作室又出新文章啦
            ## [Cheat Engine 自带入门教程 (下)](https://galaxy-studio.ga/2020/05/10/cetu2)
            ![icon](https://raw.githubusercontent.com/Galaxy-Studio-Team/sources/master/Cheat-Engine.png)
            ## [星际工作室官网：galaxy-studio.ga](https://galaxy-studio.ga)
            > 星际工作室智能推送
