name: dingtalk

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dingtalk robot message
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK}}
          type: markdown
          content: |
            # **发布频道推送**
            ## 星际工作室魔方游戏正式发布！
            ## 小小魔方，大大梦想。随时随地，享受大千世界！
            ![The-Cube](https://raw.githubusercontent.com/Galaxy-Studio-Team/sources/master/The-Cube.png)
            ### [点击此处立即体验](https://galaxy-studio.ga/cube)
            
            ## 另附赠品：滑稽[嘿嘿]
            ### [点击此处立即体验](https://galaxy-studio.ga/huaji)
            
            > 星际工作室智能推送
